### ISSUE TITLE
feat: add run_pkasolver.py

### ISSUE THREAD

**Issue by jingyu-lee-st** [Standigm/pkasolver#1]
run_pkasolver는 pkasolver.query를 Standigm의 목적에 맞게 수정한 모듈로,
Stella에서 OE Ligprep 실행 중 pkasolver을 사용하기 위해 실행됨

현재 run_pkasolver는 chemtools.lib에 있으나, 
OE Ligprep, 혹은 그 외의 용도를 위해 pkasolver를 사용해야 할 때, chemtools 없이 본 repo 만을 설치하면 되도록 하고자 함

**Comment by lee-jin-gyu96** [comment]
run_pkasolver를 그대로 쓰지 않고자 하고 있기에 일단 close함
